# Generated by Django 4.2.23 on 2025-07-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='محظور من الحجز'),
        ),
        migrations.AddField(
            model_name='profile',
            name='non_serious_reports',
            field=models.IntegerField(default=0, verbose_name='عدد الإبلاغات عن عدم الجدية'),
        ),
    ]
