# Generated by Django 4.2.23 on 2025-07-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(verbose_name='وصف الشقة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري')),
                ('apartment_type', models.CharField(choices=[('studio', 'استوديو'), ('1bhk', 'غرفة وصالة'), ('2bhk', 'غرفتين وصالة'), ('3bhk', 'ثلاث غرف وصالة'), ('shared', 'سكن مشترك'), ('room', 'غرفة'), ('bed', 'سرير في مشاركة')], max_length=10, verbose_name='نوع السكن')),
                ('area', models.IntegerField(verbose_name='المساحة بالمتر المربع')),
                ('bedrooms', models.IntegerField(verbose_name='عدد غرف النوم')),
                ('bathrooms', models.IntegerField(verbose_name='عدد الحمامات')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('distance_to_university', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='المسافة للجامعة (كم)')),
                ('walking_time', models.IntegerField(blank=True, null=True, verbose_name='الوقت مشياً (دقائق)')),
                ('driving_time', models.IntegerField(blank=True, null=True, verbose_name='الوقت بالسيارة (دقائق)')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('furnished', models.BooleanField(default=False, verbose_name='مفروش')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='يوجد واي فاي')),
                ('has_ac', models.BooleanField(default=False, verbose_name='يوجد تكييف')),
                ('has_parking', models.BooleanField(default=False, verbose_name='يوجد موقف سيارات')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='حالة الإعلان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('gender', models.CharField(choices=[('male', 'ذكور'), ('female', 'إناث'), ('all', 'الجميع')], default='all', max_length=10, verbose_name='مخصص لـ')),
                ('payment_method', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'كل 3 شهور'), ('yearly', 'سنوي')], default='monthly', max_length=10, verbose_name='طريقة الدفع')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ التأمين')),
                ('bills_included', models.BooleanField(default=False, verbose_name='تشمل الفواتير')),
                ('max_people', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للأشخاص')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='الطابق')),
                ('conditions', models.TextField(blank=True, null=True, verbose_name='شروط السكن')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='وصف إضافي')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المعلن')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('whatsapp_available', models.BooleanField(default=False, verbose_name='متاح على واتساب')),
                ('advertiser_type', models.CharField(choices=[('owner', 'صاحب الشقة'), ('agent', 'وسيط / سمسار')], default='owner', max_length=10, verbose_name='نوع المعلن')),
                ('additional_contact', models.TextField(blank=True, null=True, verbose_name='طرق تواصل إضافية')),
                ('google_maps_link', models.URLField(blank=True, null=True, verbose_name='رابط خرائط جوجل')),
                ('has_fridge', models.BooleanField(default=False, verbose_name='يوجد ثلاجة')),
                ('has_washer', models.BooleanField(default=False, verbose_name='يوجد غسالة')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='يوجد مطبخ')),
                ('has_private_bathroom', models.BooleanField(default=False, verbose_name='يوجد حمام خاص')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='يوجد بلكونة')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'شقة',
                'verbose_name_plural': 'الشقق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('non_serious', 'غير جاد')], default='pending', max_length=15, verbose_name='الحالة')),
                ('message', models.TextField(blank=True, null=True, verbose_name='رسالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apartments.apartment', verbose_name='الشقة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apartments.apartment', verbose_name='الشقة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='apartments.comment', verbose_name='التعليق الأصلي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجامعة')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسار الصورة')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_request', 'طلب حجز'), ('booking_approved', 'تمت الموافقة على الحجز'), ('booking_rejected', 'تم رفض الحجز'), ('apartment_approved', 'تمت الموافقة على الشقة'), ('apartment_rejected', 'تم رفض الشقة'), ('apartment_pending', 'شقة جديدة بحاجة للموافقة'), ('new_comment', 'تعليق جديد'), ('comment_reply', 'رد على تعليق'), ('non_serious_booking', 'حجز غير جاد'), ('user_banned', 'تم حظر المستخدم')], max_length=20, verbose_name='نوع التنبيه')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('related_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apartments.apartment', verbose_name='الشقة المتعلقة')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apartments.booking', verbose_name='الحجز المتعلق')),
                ('related_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apartments.comment', verbose_name='التعليق المتعلق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/', verbose_name='الصورة')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartments.apartment', verbose_name='الشقة')),
            ],
            options={
                'verbose_name': 'صورة الشقة',
                'verbose_name_plural': 'صور الشقق',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='apartments.university', verbose_name='الجامعة القريبة'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='apartments.apartment', verbose_name='الشقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'apartment')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1 - سيء جداً'), (2, '2 - سيء'), (3, '3 - متوسط'), (4, '4 - جيد'), (5, '5 - ممتاز')], verbose_name='التقييم')),
                ('review', models.TextField(blank=True, null=True, verbose_name='المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apartments.apartment', verbose_name='الشقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'apartment')},
            },
        ),
    ]
