# Generated by Django 4.2.23 on 2025-07-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - سيء جداً'), (2, '2 - سيء'), (3, '3 - متوسط'), (4, '4 - جيد'), (5, '5 - ممتاز')], verbose_name='التقييم')),
                ('review', models.TextField(blank=True, null=True, verbose_name='الرأي')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم الموقع',
                'verbose_name_plural': 'تقييمات الموقع',
                'ordering': ['-created_at'],
            },
        ),
    ]
