# Generated by Django 4.2.23 on 2025-07-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_siterating'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
    ]
